name: hear-validator on baselines

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        model: [naive, tf.naive, keras.naive, vggish, wav2vec2, torchopenl3, torchcrepe, vqt]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: apt-get
      run: |
        sudo apt-get install -y libsndfile-dev
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install hearvalidator
#    - name: Get model weights
#      run: |
#        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline.pt
#        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline_tf.npy
#        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline_keras.h5
#        hear-validator hearbaseline --model ./naive_baseline.pt
#        hear-validator hearbaseline.tf.naive --model ./naive_baseline_tf.npy
#        hear-validator hearbaseline.keras.naive --model ./naive_baseline_keras.h5
    - name: Validate hearbaseline (${{ matrix.model }})
      run: |
        hear-validator hearbaseline.${{ matrix.model }}
